spring:  profiles:    active: prod

---
spring:  profiles: prod
server:
  port: 8080  servlet:    context-path: /
    
---

spring:
  profiles: dev

server:
  port: 8090
  servlet:
    context-path: /jt